// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: umee/metoken/v1/events.proto

package metoken

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventSwap is emitted on Msg/Swap
type EventSwap struct {
	// meToken recipient bech32 address.
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Asset provided for the swap.
	Asset types.Coin `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset"`
	// meToken received by the recipient in exchange for the provided asset.
	Metoken types.Coin `protobuf:"bytes,3,opt,name=metoken,proto3" json:"metoken"`
}

func (m *EventSwap) Reset()         { *m = EventSwap{} }
func (m *EventSwap) String() string { return proto.CompactTextString(m) }
func (*EventSwap) ProtoMessage()    {}
func (*EventSwap) Descriptor() ([]byte, []int) {
	return fileDescriptor_503099fd3bb02aa5, []int{0}
}
func (m *EventSwap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSwap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSwap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSwap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSwap.Merge(m, src)
}
func (m *EventSwap) XXX_Size() int {
	return m.Size()
}
func (m *EventSwap) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSwap.DiscardUnknown(m)
}

var xxx_messageInfo_EventSwap proto.InternalMessageInfo

// EventRedeem is emitted on Msg/Redeem
type EventRedeem struct {
	// Asset recipient bech32 address.
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// meToken provided for the redemption.
	Metoken types.Coin `protobuf:"bytes,2,opt,name=metoken,proto3" json:"metoken"`
	// Asset received by the recipient in exchange for the provided meToken.
	Asset types.Coin `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset"`
}

func (m *EventRedeem) Reset()         { *m = EventRedeem{} }
func (m *EventRedeem) String() string { return proto.CompactTextString(m) }
func (*EventRedeem) ProtoMessage()    {}
func (*EventRedeem) Descriptor() ([]byte, []int) {
	return fileDescriptor_503099fd3bb02aa5, []int{1}
}
func (m *EventRedeem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRedeem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRedeem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRedeem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRedeem.Merge(m, src)
}
func (m *EventRedeem) XXX_Size() int {
	return m.Size()
}
func (m *EventRedeem) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRedeem.DiscardUnknown(m)
}

var xxx_messageInfo_EventRedeem proto.InternalMessageInfo

// EventRebalancing is emitted when a reserve re-balancing occurs.
type EventRebalancing struct {
	// Initial liquidity of every asset in the Index before re-balancing.
	InitialLiquidity []IndexLiquidity `protobuf:"bytes,1,rep,name=initial_liquidity,json=initialLiquidity,proto3" json:"initial_liquidity"`
	// Resultant liquidity of every asset in the Index after re-balancing.
	ResultantLiquidity []IndexLiquidity `protobuf:"bytes,2,rep,name=resultant_liquidity,json=resultantLiquidity,proto3" json:"resultant_liquidity"`
}

func (m *EventRebalancing) Reset()         { *m = EventRebalancing{} }
func (m *EventRebalancing) String() string { return proto.CompactTextString(m) }
func (*EventRebalancing) ProtoMessage()    {}
func (*EventRebalancing) Descriptor() ([]byte, []int) {
	return fileDescriptor_503099fd3bb02aa5, []int{2}
}
func (m *EventRebalancing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRebalancing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRebalancing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRebalancing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRebalancing.Merge(m, src)
}
func (m *EventRebalancing) XXX_Size() int {
	return m.Size()
}
func (m *EventRebalancing) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRebalancing.DiscardUnknown(m)
}

var xxx_messageInfo_EventRebalancing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EventSwap)(nil), "umeenetwork.umee.metoken.v1.EventSwap")
	proto.RegisterType((*EventRedeem)(nil), "umeenetwork.umee.metoken.v1.EventRedeem")
	proto.RegisterType((*EventRebalancing)(nil), "umeenetwork.umee.metoken.v1.EventRebalancing")
}

func init() { proto.RegisterFile("umee/metoken/v1/events.proto", fileDescriptor_503099fd3bb02aa5) }

var fileDescriptor_503099fd3bb02aa5 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcb, 0x8e, 0xd3, 0x30,
	0x18, 0x85, 0xe3, 0x96, 0x8b, 0xea, 0x6e, 0x86, 0x30, 0x8b, 0xcc, 0x0c, 0x32, 0x55, 0x57, 0x45,
	0x68, 0x6c, 0x65, 0xb8, 0x48, 0x2c, 0x29, 0x42, 0x08, 0x89, 0x55, 0xbb, 0x63, 0x41, 0xe5, 0x24,
	0xbf, 0x82, 0xd5, 0xc4, 0x6e, 0x63, 0x27, 0x6d, 0xdf, 0x82, 0x87, 0x01, 0xf1, 0x0a, 0x5d, 0x56,
	0x2c, 0x10, 0x2b, 0x04, 0xed, 0x8b, 0xa0, 0x24, 0xee, 0x45, 0x2c, 0x10, 0xed, 0xce, 0xbf, 0xcf,
	0x39, 0x3e, 0x9f, 0xa5, 0x1f, 0x3f, 0xc8, 0x53, 0x00, 0x96, 0x82, 0x51, 0x63, 0x90, 0xac, 0xf0,
	0x19, 0x14, 0x20, 0x8d, 0xa6, 0x93, 0x4c, 0x19, 0xe5, 0x5e, 0x95, 0xaa, 0x04, 0x33, 0x53, 0xd9,
	0x98, 0x96, 0x67, 0x6a, 0x9d, 0xb4, 0xf0, 0x2f, 0xcf, 0x63, 0x15, 0xab, 0xca, 0xc7, 0xca, 0x53,
	0x1d, 0xb9, 0xbc, 0x08, 0x95, 0x4e, 0x95, 0x1e, 0xd5, 0x42, 0x3d, 0x58, 0x89, 0xd4, 0x13, 0x0b,
	0xb8, 0x06, 0x56, 0xf8, 0x01, 0x18, 0xee, 0xb3, 0x50, 0x09, 0x69, 0xf5, 0xab, 0xbf, 0x59, 0xa6,
	0x39, 0x64, 0x8b, 0x5a, 0xec, 0x7e, 0x41, 0xb8, 0xf5, 0xba, 0x64, 0x1b, 0xce, 0xf8, 0xc4, 0x7d,
	0x8e, 0x5b, 0x19, 0x84, 0x62, 0x22, 0x40, 0x1a, 0x0f, 0x75, 0x50, 0xaf, 0xd5, 0xf7, 0xbe, 0x7d,
	0xbe, 0x3e, 0xb7, 0x7d, 0x2f, 0xa3, 0x28, 0x03, 0xad, 0x87, 0x26, 0x13, 0x32, 0x1e, 0xec, 0xad,
	0xee, 0x33, 0x7c, 0x9b, 0x6b, 0x0d, 0xc6, 0x6b, 0x74, 0x50, 0xaf, 0x7d, 0x73, 0x41, 0x6d, 0xa0,
	0x44, 0xa2, 0x16, 0x89, 0xbe, 0x52, 0x42, 0xf6, 0x6f, 0x2d, 0x7f, 0x3e, 0x74, 0x06, 0xb5, 0xdb,
	0x7d, 0x81, 0xef, 0x5a, 0x2c, 0xaf, 0xf9, 0x7f, 0xc1, 0xad, 0xbf, 0xfb, 0x15, 0xe1, 0x76, 0xc5,
	0x3d, 0x80, 0x08, 0x20, 0x3d, 0x99, 0xfc, 0x00, 0xa1, 0x71, 0x1c, 0xc2, 0xfe, 0xd3, 0xcd, 0x63,
	0x3e, 0xdd, 0xfd, 0x8e, 0xf0, 0x99, 0x25, 0x0f, 0x78, 0xc2, 0x65, 0x28, 0x64, 0xec, 0x7e, 0xc0,
	0xf7, 0x84, 0x14, 0x46, 0xf0, 0x64, 0x94, 0x88, 0x69, 0x2e, 0x22, 0x61, 0x16, 0x1e, 0xea, 0x34,
	0x7b, 0xed, 0x9b, 0xc7, 0xf4, 0x1f, 0xdb, 0x42, 0xdf, 0xca, 0x08, 0xe6, 0xef, 0xb6, 0x11, 0xdb,
	0x74, 0x66, 0xdf, 0xda, 0xdd, 0xbb, 0x01, 0xbe, 0x9f, 0x81, 0xce, 0x13, 0xc3, 0xa5, 0x39, 0x68,
	0x68, 0x9c, 0xda, 0xe0, 0xee, 0x5e, 0xdb, 0x2b, 0x6f, 0x96, 0xbf, 0x89, 0xb3, 0x5c, 0x13, 0xb4,
	0x5a, 0x13, 0xf4, 0x6b, 0x4d, 0xd0, 0xa7, 0x0d, 0x71, 0x56, 0x1b, 0xe2, 0xfc, 0xd8, 0x10, 0xe7,
	0xfd, 0xa3, 0x58, 0x98, 0x8f, 0x79, 0x40, 0x43, 0x95, 0xb2, 0xb2, 0xe2, 0xda, 0xf6, 0x55, 0x03,
	0x2b, 0x9e, 0xb2, 0xf9, 0x76, 0x45, 0x83, 0x3b, 0xd5, 0x6a, 0x3e, 0xf9, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x9e, 0x6d, 0x59, 0x45, 0x03, 0x00, 0x00,
}

func (m *EventSwap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSwap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSwap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Metoken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRedeem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRedeem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRedeem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Metoken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRebalancing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRebalancing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRebalancing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResultantLiquidity) > 0 {
		for iNdEx := len(m.ResultantLiquidity) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResultantLiquidity[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.InitialLiquidity) > 0 {
		for iNdEx := len(m.InitialLiquidity) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitialLiquidity[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventSwap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Asset.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Metoken.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventRedeem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Metoken.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Asset.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventRebalancing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.InitialLiquidity) > 0 {
		for _, e := range m.InitialLiquidity {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	if len(m.ResultantLiquidity) > 0 {
		for _, e := range m.ResultantLiquidity {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventSwap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSwap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSwap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metoken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metoken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRedeem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRedeem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRedeem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metoken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metoken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRebalancing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRebalancing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRebalancing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialLiquidity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialLiquidity = append(m.InitialLiquidity, IndexLiquidity{})
			if err := m.InitialLiquidity[len(m.InitialLiquidity)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultantLiquidity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultantLiquidity = append(m.ResultantLiquidity, IndexLiquidity{})
			if err := m.ResultantLiquidity[len(m.ResultantLiquidity)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
