// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: umee/metoken/v1/metoken.proto

package metoken

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the metoken module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Index defines an index of assets that are allowed to swap and redeem for the Index's meToken,
// along with its metadata and parameters.
type Index struct {
	// MeToken Denom is the denomination of the Index's meToken denom that will be given to user in exchange of accepted
	// assets.
	MetokenDenom string `protobuf:"bytes,1,opt,name=metoken_denom,json=metokenDenom,proto3" json:"metoken_denom,omitempty"`
	// MeToken Max Supply is the maximum amount of Index's meTokens can be minted.
	// A swap that requires to mint more Index's meToken than this value will result in an error.
	// Must be a non negative value. 0 means that there is no limit.
	MetokenMaxSupply github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=metoken_max_supply,json=metokenMaxSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"metoken_max_supply"`
	// IndexType defines the Index Type: stable or non-stable
	IndexType string `protobuf:"bytes,3,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	// Fee are fee parameters used for swap and redemption fee calculations.
	Fee Fee `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee"`
	// Accepted Assets is the list of the Tokens that are accepted to swap and redeem for the Index's meToken.
	AcceptedAssets []AcceptedAsset `protobuf:"bytes,5,rep,name=accepted_assets,json=acceptedAssets,proto3" json:"accepted_assets"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{1}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Index.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return m.Size()
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetMetokenDenom() string {
	if m != nil {
		return m.MetokenDenom
	}
	return ""
}

func (m *Index) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *Index) GetFee() Fee {
	if m != nil {
		return m.Fee
	}
	return Fee{}
}

func (m *Index) GetAcceptedAssets() []AcceptedAsset {
	if m != nil {
		return m.AcceptedAssets
	}
	return nil
}

// Fee are the parameters used for the calculation of the fee to be applied for swaps and redemptions and charged to
// the user.
type Fee struct {
	// Min fee is the minimum fee to be charged to the user. The applied fee will tend to decrease down to this value,
	// when the accepted asset is undersupplied in the index. It must be less than Balanced and Max fees.
	// Valid values: 0-∞.
	MinFee github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=min_fee,json=minFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_fee"`
	// Balanced fee is the fee to be charged to the user when the index is balanced. It must be greater than min_fee and
	// lower than max_fee
	// Valid values: > 0.
	BalancedFee github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=balanced_fee,json=balancedFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"balanced_fee"`
	// Max fee is the maximum fee to be charged to the user. The applied fee will tend to increase up to this value,
	// when the accepted asset is oversupplied in the index. It must be greater than Min and Balanced fee. If the value
	// is 0, no Max fee will be applied.
	// Valid values: 0-∞.
	MaxFee github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=max_fee,json=maxFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_fee"`
}

func (m *Fee) Reset()         { *m = Fee{} }
func (m *Fee) String() string { return proto.CompactTextString(m) }
func (*Fee) ProtoMessage()    {}
func (*Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{2}
}
func (m *Fee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fee.Merge(m, src)
}
func (m *Fee) XXX_Size() int {
	return m.Size()
}
func (m *Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Fee proto.InternalMessageInfo

// AcceptedAsset is an asset that is accepted to participate in the Index's swaps and redemptions, along with its
// metadata and parameters
type AcceptedAsset struct {
	// Asset Denom is the denomination of the underlying asset. Must be the base
	// denom as registered in the Bank module (so IBC denom for IBC tokens).
	AssetDenom string `protobuf:"bytes,1,opt,name=asset_denom,json=assetDenom,proto3" json:"asset_denom,omitempty"`
	// Reserve portion is the portion of swapped assets that will be transferred to metoken module as reserves, and the
	// portion that will be taken from metoken module reserves when a redemption occurs.
	// Valid values: 0-1.
	ReservePortion github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=reserve_portion,json=reservePortion,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reserve_portion"`
	// Target allocation is the portion of an accepted asset the Index is targeting to have. This value will be
	// calculated in the addition and the update of an Index, as well as when an asset is deleted from it. The value
	// would be 1/amount of assets in the Index.
	TargetAllocation *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=target_allocation,json=targetAllocation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"target_allocation,omitempty"`
}

func (m *AcceptedAsset) Reset()         { *m = AcceptedAsset{} }
func (m *AcceptedAsset) String() string { return proto.CompactTextString(m) }
func (*AcceptedAsset) ProtoMessage()    {}
func (*AcceptedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{3}
}
func (m *AcceptedAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AcceptedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AcceptedAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AcceptedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptedAsset.Merge(m, src)
}
func (m *AcceptedAsset) XXX_Size() int {
	return m.Size()
}
func (m *AcceptedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptedAsset proto.InternalMessageInfo

func (m *AcceptedAsset) GetAssetDenom() string {
	if m != nil {
		return m.AssetDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "umeenetwork.umee.metoken.v1.Params")
	proto.RegisterType((*Index)(nil), "umeenetwork.umee.metoken.v1.Index")
	proto.RegisterType((*Fee)(nil), "umeenetwork.umee.metoken.v1.Fee")
	proto.RegisterType((*AcceptedAsset)(nil), "umeenetwork.umee.metoken.v1.AcceptedAsset")
}

func init() { proto.RegisterFile("umee/metoken/v1/metoken.proto", fileDescriptor_dda977db8ad52437) }

var fileDescriptor_dda977db8ad52437 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb3, 0x71, 0x1a, 0xd4, 0x4d, 0x9b, 0x96, 0x15, 0x07, 0x0b, 0x54, 0x27, 0x2a, 0x12,
	0x0a, 0x48, 0xb5, 0xd5, 0xc2, 0x01, 0x71, 0x4b, 0xa8, 0x82, 0x7a, 0x40, 0x2a, 0x01, 0x09, 0xf1,
	0x47, 0xb2, 0x36, 0xf6, 0x10, 0xac, 0x64, 0x77, 0x2d, 0xef, 0x26, 0x38, 0x6f, 0xc1, 0x23, 0xf0,
	0x30, 0x1c, 0x7a, 0xec, 0x11, 0x71, 0xa8, 0x50, 0x72, 0xe1, 0xc0, 0x81, 0x47, 0x40, 0xbb, 0x5e,
	0xd3, 0xf6, 0x52, 0x29, 0x39, 0x79, 0x3c, 0x3b, 0xf3, 0xdb, 0xef, 0x1b, 0xcd, 0xe2, 0xbd, 0x29,
	0x03, 0x08, 0x18, 0x28, 0x31, 0x06, 0x1e, 0xcc, 0x0e, 0xcb, 0xd0, 0x4f, 0x33, 0xa1, 0x04, 0xb9,
	0xa7, 0x8f, 0x39, 0xa8, 0x2f, 0x22, 0x1b, 0xfb, 0x3a, 0xf6, 0xcb, 0xf3, 0xd9, 0xe1, 0xdd, 0x3b,
	0x23, 0x31, 0x12, 0xa6, 0x2e, 0xd0, 0x51, 0xd1, 0xb2, 0xdf, 0xc4, 0xf5, 0x53, 0x9a, 0x51, 0x26,
	0x9f, 0xd5, 0x7e, 0x7f, 0x6b, 0xa1, 0xfd, 0xef, 0x55, 0xbc, 0x71, 0xc2, 0x63, 0xc8, 0xc9, 0x7d,
	0xbc, 0x6d, 0xbb, 0xc3, 0x18, 0xb8, 0x60, 0x2e, 0x6a, 0xa3, 0xce, 0xe6, 0x60, 0xcb, 0x26, 0x8f,
	0x75, 0x8e, 0x7c, 0xc4, 0xa4, 0x2c, 0x62, 0x34, 0x0f, 0xe5, 0x34, 0x4d, 0x27, 0x73, 0xb7, 0xaa,
	0x2b, 0x7b, 0xfe, 0xd9, 0x45, 0xab, 0xf2, 0xf3, 0xa2, 0xf5, 0x60, 0x94, 0xa8, 0xcf, 0xd3, 0xa1,
	0x1f, 0x09, 0x16, 0x44, 0x42, 0x32, 0x21, 0xed, 0xe7, 0x40, 0xc6, 0xe3, 0x40, 0xcd, 0x53, 0x90,
	0xfe, 0x09, 0x57, 0x83, 0x5d, 0x4b, 0x7a, 0x49, 0xf3, 0xd7, 0x86, 0x43, 0xf6, 0x30, 0x4e, 0xb4,
	0x96, 0x50, 0x17, 0xb9, 0x8e, 0xb9, 0x7f, 0xd3, 0x64, 0xde, 0xcc, 0x53, 0x20, 0x4f, 0xb1, 0xf3,
	0x09, 0xc0, 0xad, 0xb5, 0x51, 0xa7, 0x71, 0xd4, 0xf6, 0x6f, 0x30, 0xef, 0xf7, 0x01, 0x7a, 0x35,
	0xad, 0x67, 0xa0, 0x5b, 0xc8, 0x3b, 0xbc, 0x43, 0xa3, 0x08, 0x52, 0x05, 0x71, 0x48, 0xa5, 0x04,
	0x25, 0xdd, 0x8d, 0xb6, 0xd3, 0x69, 0x1c, 0x3d, 0xba, 0x91, 0xd2, 0xb5, 0x3d, 0x5d, 0xdd, 0x62,
	0x79, 0x4d, 0x7a, 0x35, 0x59, 0x8e, 0xf1, 0x2f, 0xc2, 0x4e, 0x1f, 0x80, 0xbc, 0xc0, 0xb7, 0x58,
	0xc2, 0x43, 0x2d, 0x13, 0xad, 0x3c, 0x94, 0x63, 0x88, 0x06, 0x75, 0x96, 0x70, 0x0d, 0x7a, 0x85,
	0xb7, 0x86, 0x74, 0x42, 0x79, 0x04, 0xb1, 0xa1, 0x55, 0xd7, 0xa2, 0x35, 0x4a, 0x46, 0xa9, 0x8d,
	0xe6, 0x86, 0xe6, 0xac, 0xa9, 0x8d, 0xe6, 0x7d, 0x00, 0x6b, 0xf9, 0x0f, 0xc2, 0xdb, 0xd7, 0x06,
	0x44, 0x5a, 0xb8, 0x61, 0x86, 0x7b, 0x6d, 0x7f, 0xb0, 0x49, 0x15, 0xdb, 0xf3, 0x16, 0xef, 0x64,
	0x20, 0x21, 0x9b, 0x41, 0x98, 0x8a, 0x4c, 0x25, 0x82, 0xaf, 0xe9, 0xab, 0x69, 0x31, 0xa7, 0x05,
	0x85, 0x7c, 0xc0, 0xb7, 0x15, 0xcd, 0x46, 0xa0, 0x42, 0x3a, 0x99, 0x88, 0x88, 0x1a, 0xf4, 0xa5,
	0x49, 0xb4, 0x02, 0x7a, 0xb7, 0x00, 0x75, 0xff, 0x73, 0x0a, 0xbb, 0xbd, 0xe7, 0x67, 0x0b, 0x0f,
	0x9d, 0x2f, 0x3c, 0xf4, 0x6b, 0xe1, 0xa1, 0xaf, 0x4b, 0xaf, 0x72, 0xbe, 0xf4, 0x2a, 0x3f, 0x96,
	0x5e, 0xe5, 0xfd, 0xc3, 0x2b, 0x64, 0xbd, 0x41, 0x07, 0x76, 0x9d, 0xcc, 0x4f, 0x30, 0x7b, 0x12,
	0xe4, 0xe5, 0xb3, 0x1d, 0xd6, 0xcd, 0x23, 0x7c, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x15, 0x1f,
	0x73, 0xcf, 0xd8, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Index) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Index)
	if !ok {
		that2, ok := that.(Index)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MetokenDenom != that1.MetokenDenom {
		return false
	}
	if !this.MetokenMaxSupply.Equal(that1.MetokenMaxSupply) {
		return false
	}
	if this.IndexType != that1.IndexType {
		return false
	}
	if !this.Fee.Equal(&that1.Fee) {
		return false
	}
	if len(this.AcceptedAssets) != len(that1.AcceptedAssets) {
		return false
	}
	for i := range this.AcceptedAssets {
		if !this.AcceptedAssets[i].Equal(&that1.AcceptedAssets[i]) {
			return false
		}
	}
	return true
}
func (this *Fee) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Fee)
	if !ok {
		that2, ok := that.(Fee)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinFee.Equal(that1.MinFee) {
		return false
	}
	if !this.BalancedFee.Equal(that1.BalancedFee) {
		return false
	}
	if !this.MaxFee.Equal(that1.MaxFee) {
		return false
	}
	return true
}
func (this *AcceptedAsset) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AcceptedAsset)
	if !ok {
		that2, ok := that.(AcceptedAsset)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AssetDenom != that1.AssetDenom {
		return false
	}
	if !this.ReservePortion.Equal(that1.ReservePortion) {
		return false
	}
	if that1.TargetAllocation == nil {
		if this.TargetAllocation != nil {
			return false
		}
	} else if !this.TargetAllocation.Equal(*that1.TargetAllocation) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Index) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Index) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Index) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AcceptedAssets) > 0 {
		for iNdEx := len(m.AcceptedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AcceptedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetoken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.IndexType) > 0 {
		i -= len(m.IndexType)
		copy(dAtA[i:], m.IndexType)
		i = encodeVarintMetoken(dAtA, i, uint64(len(m.IndexType)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.MetokenMaxSupply.Size()
		i -= size
		if _, err := m.MetokenMaxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.MetokenDenom) > 0 {
		i -= len(m.MetokenDenom)
		copy(dAtA[i:], m.MetokenDenom)
		i = encodeVarintMetoken(dAtA, i, uint64(len(m.MetokenDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Fee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxFee.Size()
		i -= size
		if _, err := m.MaxFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.BalancedFee.Size()
		i -= size
		if _, err := m.BalancedFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MinFee.Size()
		i -= size
		if _, err := m.MinFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AcceptedAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AcceptedAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AcceptedAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TargetAllocation != nil {
		{
			size := m.TargetAllocation.Size()
			i -= size
			if _, err := m.TargetAllocation.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMetoken(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.ReservePortion.Size()
		i -= size
		if _, err := m.ReservePortion.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.AssetDenom) > 0 {
		i -= len(m.AssetDenom)
		copy(dAtA[i:], m.AssetDenom)
		i = encodeVarintMetoken(dAtA, i, uint64(len(m.AssetDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetoken(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetoken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Index) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MetokenDenom)
	if l > 0 {
		n += 1 + l + sovMetoken(uint64(l))
	}
	l = m.MetokenMaxSupply.Size()
	n += 1 + l + sovMetoken(uint64(l))
	l = len(m.IndexType)
	if l > 0 {
		n += 1 + l + sovMetoken(uint64(l))
	}
	l = m.Fee.Size()
	n += 1 + l + sovMetoken(uint64(l))
	if len(m.AcceptedAssets) > 0 {
		for _, e := range m.AcceptedAssets {
			l = e.Size()
			n += 1 + l + sovMetoken(uint64(l))
		}
	}
	return n
}

func (m *Fee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinFee.Size()
	n += 1 + l + sovMetoken(uint64(l))
	l = m.BalancedFee.Size()
	n += 1 + l + sovMetoken(uint64(l))
	l = m.MaxFee.Size()
	n += 1 + l + sovMetoken(uint64(l))
	return n
}

func (m *AcceptedAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetDenom)
	if l > 0 {
		n += 1 + l + sovMetoken(uint64(l))
	}
	l = m.ReservePortion.Size()
	n += 1 + l + sovMetoken(uint64(l))
	if m.TargetAllocation != nil {
		l = m.TargetAllocation.Size()
		n += 1 + l + sovMetoken(uint64(l))
	}
	return n
}

func sovMetoken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetoken(x uint64) (n int) {
	return sovMetoken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Index) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Index: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Index: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetokenMaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MetokenMaxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IndexType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedAssets = append(m.AcceptedAssets, AcceptedAsset{})
			if err := m.AcceptedAssets[len(m.AcceptedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalancedFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BalancedFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AcceptedAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AcceptedAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AcceptedAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservePortion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReservePortion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.TargetAllocation = &v
			if err := m.TargetAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetoken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetoken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetoken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetoken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetoken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetoken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetoken = fmt.Errorf("proto: unexpected end of group")
)
