// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: umee/metoken/v1/metoken.proto

package metoken

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the metoken module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Index defines an index of assets that are allowed to swap and redeem for the Index's meToken,
// along with its metadata and parameters.
type Index struct {
	// MeToken Denom is the denomination of the Index's meToken denom that will be given to user in exchange of accepted
	// assets.
	MetokenDenom string `protobuf:"bytes,1,opt,name=metoken_denom,json=metokenDenom,proto3" json:"metoken_denom,omitempty"`
	// Max Incentivizing Displacement is the maximum displacement that can be applied to the original exchange rate.
	// It's used when the Denom Incentivizing Displacement is calculated for incentivizing and decentivizing swaps and
	// redemptions.
	// Valid values: 0-1.
	MaxIncentivizingDisplacement github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=max_incentivizing_displacement,json=maxIncentivizingDisplacement,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_incentivizing_displacement"`
	// MeToken Max Supply is the maximum amount of Index's meTokens can be minted.
	// A swap that requires to mint more Index's meToken than this value will result in an error.
	// Must be a non negative value. 0 means that there is no limit.
	MetokenMaxSupply github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=metoken_max_supply,json=metokenMaxSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"metoken_max_supply"`
	// Accepted Assets is the list of the Tokens that are accepted to swap and redeem for the Index's meToken.
	AcceptedAssets []AcceptedAsset `protobuf:"bytes,4,rep,name=accepted_assets,json=acceptedAssets,proto3" json:"accepted_assets"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{1}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Index.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return m.Size()
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetMetokenDenom() string {
	if m != nil {
		return m.MetokenDenom
	}
	return ""
}

func (m *Index) GetAcceptedAssets() []AcceptedAsset {
	if m != nil {
		return m.AcceptedAssets
	}
	return nil
}

// AcceptedAsset is an asset that is accepted to participate in the Index's swaps and redemptions, along with its
// metadata and parameters
type AcceptedAsset struct {
	// Asset Denom is the denomination of the underlying asset. Must be the base
	// denom as registered in the Bank module (so IBC denom for IBC tokens).
	AssetDenom string `protobuf:"bytes,1,opt,name=asset_denom,json=assetDenom,proto3" json:"asset_denom,omitempty"`
	// Reserve portion is the portion of swapped assets that will be transferred to metoken module as reserves, and the
	// portion that will be taken from metoken module reserves when a redemption occurs.
	// Valid values: 0-1.
	ReservePortion github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=reserve_portion,json=reservePortion,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reserve_portion"`
}

func (m *AcceptedAsset) Reset()         { *m = AcceptedAsset{} }
func (m *AcceptedAsset) String() string { return proto.CompactTextString(m) }
func (*AcceptedAsset) ProtoMessage()    {}
func (*AcceptedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda977db8ad52437, []int{2}
}
func (m *AcceptedAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AcceptedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AcceptedAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AcceptedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptedAsset.Merge(m, src)
}
func (m *AcceptedAsset) XXX_Size() int {
	return m.Size()
}
func (m *AcceptedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptedAsset proto.InternalMessageInfo

func (m *AcceptedAsset) GetAssetDenom() string {
	if m != nil {
		return m.AssetDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "umeenetwork.umee.metoken.v1.Params")
	proto.RegisterType((*Index)(nil), "umeenetwork.umee.metoken.v1.Index")
	proto.RegisterType((*AcceptedAsset)(nil), "umeenetwork.umee.metoken.v1.AcceptedAsset")
}

func init() { proto.RegisterFile("umee/metoken/v1/metoken.proto", fileDescriptor_dda977db8ad52437) }

var fileDescriptor_dda977db8ad52437 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0x4e, 0xda, 0x5a, 0x70, 0x6a, 0x5b, 0x09, 0x2e, 0x82, 0x3f, 0x49, 0xa9, 0x20, 0x55, 0xe8,
	0x84, 0xaa, 0x2b, 0x77, 0xad, 0xdd, 0x74, 0x21, 0x94, 0xb8, 0x10, 0x45, 0x08, 0xd3, 0xe4, 0x10,
	0x43, 0x3b, 0x33, 0x21, 0x33, 0x8d, 0xa9, 0x2f, 0xa1, 0x8f, 0xe0, 0xe3, 0x74, 0xd9, 0xa5, 0xb8,
	0x28, 0xda, 0x6e, 0xee, 0x63, 0x5c, 0x26, 0x3f, 0x90, 0x6e, 0x2e, 0xdc, 0xbb, 0x9a, 0x33, 0xdf,
	0x39, 0xdf, 0x77, 0xce, 0xf9, 0x38, 0xe8, 0xd9, 0x96, 0x02, 0x38, 0x14, 0x24, 0x5f, 0x03, 0x73,
	0xd2, 0x49, 0x15, 0xe2, 0x38, 0xe1, 0x92, 0x1b, 0x4f, 0x54, 0x9a, 0x81, 0xfc, 0xce, 0x93, 0x35,
	0x56, 0x31, 0xae, 0xf2, 0xe9, 0xe4, 0xf1, 0xa3, 0x90, 0x87, 0x3c, 0xaf, 0x73, 0x54, 0x54, 0x50,
	0x86, 0x3d, 0xd4, 0x5e, 0x92, 0x84, 0x50, 0xf1, 0xae, 0x75, 0xf5, 0xdb, 0xd6, 0x87, 0xff, 0x1b,
	0xe8, 0xde, 0x82, 0x05, 0x90, 0x19, 0xcf, 0x51, 0xb7, 0x64, 0x7b, 0x01, 0x30, 0x4e, 0x4d, 0x7d,
	0xa0, 0x8f, 0xee, 0xbb, 0x0f, 0x4a, 0x70, 0xae, 0x30, 0x43, 0x22, 0x8b, 0x92, 0xcc, 0x8b, 0x98,
	0x0f, 0x4c, 0x46, 0x69, 0xf4, 0x23, 0x62, 0xa1, 0x17, 0x44, 0x22, 0xde, 0x10, 0x1f, 0x28, 0x30,
	0x69, 0x36, 0x14, 0x6b, 0x86, 0xf7, 0x47, 0x5b, 0xfb, 0x7b, 0xb4, 0x5f, 0x84, 0x91, 0xfc, 0xb6,
	0x5d, 0x61, 0x9f, 0x53, 0xc7, 0xe7, 0x82, 0x72, 0x51, 0x3e, 0x63, 0x11, 0xac, 0x1d, 0xb9, 0x8b,
	0x41, 0xe0, 0x39, 0xf8, 0xee, 0x53, 0x4a, 0xb2, 0x45, 0x5d, 0x74, 0x5e, 0xd3, 0x34, 0xbe, 0x22,
	0xa3, 0x1a, 0x4d, 0x75, 0x17, 0xdb, 0x38, 0xde, 0xec, 0xcc, 0xe6, 0xad, 0x3b, 0x2d, 0x98, 0x74,
	0x1f, 0x96, 0x4a, 0x1f, 0x48, 0xf6, 0x31, 0xd7, 0x31, 0x3e, 0xa3, 0x3e, 0xf1, 0x7d, 0x88, 0x25,
	0x04, 0x1e, 0x11, 0x02, 0xa4, 0x30, 0x5b, 0x83, 0xe6, 0xa8, 0xf3, 0xfa, 0x15, 0xbe, 0xc1, 0x5f,
	0x3c, 0x2d, 0x39, 0x53, 0x45, 0x99, 0xb5, 0xd4, 0x18, 0x6e, 0x8f, 0xd4, 0xc1, 0xca, 0xe3, 0x9f,
	0x3a, 0xea, 0x5e, 0x54, 0x1b, 0x36, 0xea, 0xe4, 0x9d, 0x2e, 0x9c, 0x46, 0x39, 0x54, 0xf8, 0xfc,
	0x09, 0xf5, 0x13, 0x10, 0x90, 0xa4, 0xe0, 0xc5, 0x3c, 0x91, 0x11, 0x67, 0x77, 0x34, 0xb6, 0x57,
	0xca, 0x2c, 0x0b, 0x95, 0x62, 0xa2, 0xd9, 0xfb, 0xfd, 0xc9, 0xd2, 0x0f, 0x27, 0x4b, 0xff, 0x77,
	0xb2, 0xf4, 0x5f, 0x67, 0x4b, 0x3b, 0x9c, 0x2d, 0xed, 0xcf, 0xd9, 0xd2, 0xbe, 0xbc, 0xac, 0xe9,
	0xaa, 0x8d, 0xc7, 0xe5, 0xfa, 0xf9, 0xc7, 0x49, 0xdf, 0x3a, 0x59, 0x75, 0x83, 0xab, 0x76, 0x7e,
	0x51, 0x6f, 0xae, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xb1, 0xab, 0x06, 0xa5, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Index) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Index)
	if !ok {
		that2, ok := that.(Index)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MetokenDenom != that1.MetokenDenom {
		return false
	}
	if !this.MaxIncentivizingDisplacement.Equal(that1.MaxIncentivizingDisplacement) {
		return false
	}
	if !this.MetokenMaxSupply.Equal(that1.MetokenMaxSupply) {
		return false
	}
	if len(this.AcceptedAssets) != len(that1.AcceptedAssets) {
		return false
	}
	for i := range this.AcceptedAssets {
		if !this.AcceptedAssets[i].Equal(&that1.AcceptedAssets[i]) {
			return false
		}
	}
	return true
}
func (this *AcceptedAsset) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AcceptedAsset)
	if !ok {
		that2, ok := that.(AcceptedAsset)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AssetDenom != that1.AssetDenom {
		return false
	}
	if !this.ReservePortion.Equal(that1.ReservePortion) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Index) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Index) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Index) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AcceptedAssets) > 0 {
		for iNdEx := len(m.AcceptedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AcceptedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetoken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.MetokenMaxSupply.Size()
		i -= size
		if _, err := m.MetokenMaxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MaxIncentivizingDisplacement.Size()
		i -= size
		if _, err := m.MaxIncentivizingDisplacement.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.MetokenDenom) > 0 {
		i -= len(m.MetokenDenom)
		copy(dAtA[i:], m.MetokenDenom)
		i = encodeVarintMetoken(dAtA, i, uint64(len(m.MetokenDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AcceptedAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AcceptedAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AcceptedAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ReservePortion.Size()
		i -= size
		if _, err := m.ReservePortion.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMetoken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.AssetDenom) > 0 {
		i -= len(m.AssetDenom)
		copy(dAtA[i:], m.AssetDenom)
		i = encodeVarintMetoken(dAtA, i, uint64(len(m.AssetDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetoken(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetoken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Index) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MetokenDenom)
	if l > 0 {
		n += 1 + l + sovMetoken(uint64(l))
	}
	l = m.MaxIncentivizingDisplacement.Size()
	n += 1 + l + sovMetoken(uint64(l))
	l = m.MetokenMaxSupply.Size()
	n += 1 + l + sovMetoken(uint64(l))
	if len(m.AcceptedAssets) > 0 {
		for _, e := range m.AcceptedAssets {
			l = e.Size()
			n += 1 + l + sovMetoken(uint64(l))
		}
	}
	return n
}

func (m *AcceptedAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetDenom)
	if l > 0 {
		n += 1 + l + sovMetoken(uint64(l))
	}
	l = m.ReservePortion.Size()
	n += 1 + l + sovMetoken(uint64(l))
	return n
}

func sovMetoken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetoken(x uint64) (n int) {
	return sovMetoken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Index) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Index: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Index: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIncentivizingDisplacement", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxIncentivizingDisplacement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetokenMaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MetokenMaxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedAssets = append(m.AcceptedAssets, AcceptedAsset{})
			if err := m.AcceptedAssets[len(m.AcceptedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AcceptedAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AcceptedAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AcceptedAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservePortion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReservePortion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetoken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetoken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetoken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetoken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetoken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetoken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetoken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetoken = fmt.Errorf("proto: unexpected end of group")
)
